---
title: "Predict Function"
author: "Adeline Shin"
date: "3/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(caret)
library(glmnet)
```

# Loading the Data
```{r}
cancer_data = read.csv("./breast-cancer.csv")
```

# Predict Function
```{r}
predict_fcn = function(x, y, df, test_df){
  # Parameters
  ctrl = trainControl(method = "repeatedcv", number = 5, repeats = 5)
  ncomp = length(df)
  
  # Model
  ridge_fit = train(x, y,
                    method = "glmnet", # Can be changed to another method
                    trControl = ctrl,
                    tuneGrid = expand.grid(alpha = 0, 
                                           lambda = exp(seq(-5, 5, length = 100))))
  plot(ridge_fit, xTrans = function(x) log(x))
  
  # Prediction and Fit
  ridge_pred = predict(ridge_fit, newdata = test_df)
  ridge_mse = mse(test_df$test_y, ridge_pred)
}
```

# Comparing logistic lasso data with actual data
```{r}
rmse = function(x, y) {
  actual_diagnosis = cancer_data$diagnosis 
  actual_diagnosis = as.data.frame(recode(actual_diagnosis, "B" = 0, "M" = 1))
  
  i = 1
  lambda_vec = exp(seq(-5, 0, 0.05))
  rmse_vec = rep(0, length(lambda_vec))
  while (i <= length(lambda_vec)) {
    lasso_lambda = logit_lasso(x, y, lambda_vec[i], tol = 0.01, include_zero_lambda = FALSE)
    predict_result = predict(lasso_lambda, x)
    rmse = (sum(actual_diagnosis - predict_result))^2 / 569
    rmse_vec[i] = rmse
    i = i + 1
  }
  return(rmse_vec)
}

rmse_vector = rmse(x, y)
lambda_vector = exp(seq(-5, 0, 0.05))

plot(lambda_vector, rmse_vector)
```

